config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :friends
  authenticated :user do
    root 'friends#index', as: "authenticated_root"
  end
  root 'welcome#index'
end

app/models/friend.rb
class Friend < ActiveRecord::Base
    belongs_to :user
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "50x50>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
    before_action :find_friend, only: [:show, :update, :destroy, :edit]
    
    def index
        @friends = Friend.where(user_id: current_user)
    end
    def new
        @friend = current_user.friends.build
    end
    
    def create
        @friend = current_user.friends.build(friend_params)
        if @friend.save
            redirect_to @friend
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @friend.update(friend_params)
            redirect_to @friend
        else
            render 'edit'
        end
    end
    
    def destroy
        @friend.destroy
        redirect_to friends_path
    end
    
    def show
    end
    
    private
    
    def find_friend
        @friend = Friend.find(params[:id])
    end
    
    def friend_params
        params.require(:friend).permit(:name, :birthday, :email, :phone, :feeling, :avatar)
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_form.html.erb
<%= simple_form_for @friend do |f| %>
  <%= f.input :name %>
  <%= f.input :birthday %>
  <%= f.input :email %>
  <%= f.input :phone %>
  <%= f.input :feeling %>
  <%= f.input :avatar, as: :file %>
  <%= f.button :submit %>
<% end %>

app/views/friends/edit.html.erb
<div class="container" style="background-color:#FFC1C1">
    <h1 > Editting</h1>
    <div class="col-md-6 col-md-offset-3 form">
        <%= render 'form' %>
        <%= link_to "Cancel", friend_path %>
    </div>
</div>

app/views/friends/index.html.erb
<div class="row">
  <% @friends.each do |friend| %>
    <div class="col-sm-6 col-md-5 friend">
      <p>
        <%= image_tag friend.avatar.url(:thumb) %>
   <%= link_to friend.name, friend %>
  </p>
  <p>
    <strong>Birthday:</strong>
    <%= friend.birthday %>
  </p>
  <p>
    <strong>Email:</strong>
    <%= friend.email %><br>
  </p>
  <p>
    <strong>Phone:</strong>
    <%= friend.phone %><br>
  </p>
  <p>
    <strong>Feeling:</strong>
    <%= friend.feeling %><br>
  </p>
    </div>
<% end %>
</div>
<%= link_to "New Friend", new_friend_path %>

app/views/friends/new.html.erb
<div class="container"  style="background-color:#FFC1C1">
  <h1 style="color:#32CD32"> Add a new Friend</h1>
  <div class="col-md-6 col-md-offset-3 form">
    <%= render 'form'%>
  </div>
</div>

app/views/friends/show.html.erb
<div  class="container" style="background-color: rgb(255, 231, 186)">
    <div class="col-md-10 row col-md-offset-1">
        <div class="col-md-4">
            <%= image_tag @friend.avatar.url(:medium) %>
        </div>
        <div class="col-md-8">
            <p>
               <strong>name :</strong>     <%= @friend.name %><br>
               <strong>birthday :</strong> <%= @friend.birthday %><br>
               <strong>email :</strong>    <%= @friend.email %><br>
               <strong>phone :</strong>    <%= @friend.phone %><br>
               <strong>feeling :</strong>  <%= @friend.feeling %><br>
            </p>
            <%= link_to "Edit", edit_friend_path(@friend) %>
            <%= link_to "Delete", friend_path(@friend), method: :delete, data: {confirm: "Bạn có chắc chắn muốn xoá?"} %>
        </div>
        <%= link_to "All Friend", friends_path %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyFriend</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "my friend", root_path, id: "logo" %>
    <nav>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "New Friend", new_friend_path %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Log in", new_user_session_path%></li>
        </ul>
      <% end %>
    </nav>
  </div>
</header>
<div class="container" styles="color:blue">
  <%= yield %>
</div>

</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | My Event Application</title>
  </head>
  <body>
    <div class="center jumbotron image">
        <h1>Welcome to the My Friend</h1>
        <h2>This is the home page for the My Friend application</h2>
        <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
    </div>
  </body>
</html>